import { StyleSheet } from 'react-native';

export const myMargin = StyleSheet.create({
    margin1: { margin: 1 },
    marginX1: { marginHorizontal: 1 },
    marginY1: { marginVertical: 1 },
    marginL1: { marginLeft: 1 },
    marginR1: { marginRight: 1 },
    marginT1: { marginTop: 1 },
    marginB1: { marginBottom: 1 },

    margin2: { margin: 2 },
    marginX2: { marginHorizontal: 2 },
    marginY2: { marginVertical: 2 },
    marginL2: { marginLeft: 2 },
    marginR2: { marginRight: 2 },
    marginT2: { marginTop: 2 },
    marginB2: { marginBottom: 2 },

    margin3: { margin: 3 },
    marginX3: { marginHorizontal: 3 },
    marginY3: { marginVertical: 3 },
    marginL3: { marginLeft: 3 },
    marginR3: { marginRight: 3 },
    marginT3: { marginTop: 3 },
    marginB3: { marginBottom: 3 },

    margin4: { margin: 4 },
    marginX4: { marginHorizontal: 4 },
    marginY4: { marginVertical: 4 },
    marginL4: { marginLeft: 4 },
    marginR4: { marginRight: 4 },
    marginT4: { marginTop: 4 },
    marginB4: { marginBottom: 4 },

    margin5: { margin: 5 },
    marginX5: { marginHorizontal: 5 },
    marginY5: { marginVertical: 5 },
    marginL5: { marginLeft: 5 },
    marginR5: { marginRight: 5 },
    marginT5: { marginTop: 5 },
    marginB5: { marginBottom: 5 },

    margin6: { margin: 6 },
    marginX6: { marginHorizontal: 6 },
    marginY6: { marginVertical: 6 },
    marginL6: { marginLeft: 6 },
    marginR6: { marginRight: 6 },
    marginT6: { marginTop: 6 },
    marginB6: { marginBottom: 6 },

    margin7: { margin: 7 },
    marginX7: { marginHorizontal: 7 },
    marginY7: { marginVertical: 7 },
    marginL7: { marginLeft: 7 },
    marginR7: { marginRight: 7 },
    marginT7: { marginTop: 7 },
    marginB7: { marginBottom: 7 },

    margin8: { margin: 8 },
    marginX8: { marginHorizontal: 8 },
    marginY8: { marginVertical: 8 },
    marginL8: { marginLeft: 8 },
    marginR8: { marginRight: 8 },
    marginT8: { marginTop: 8 },
    marginB8: { marginBottom: 8 },

    margin9: { margin: 9 },
    marginX9: { marginHorizontal: 9 },
    marginY9: { marginVertical: 9 },
    marginL9: { marginLeft: 9 },
    marginR9: { marginRight: 9 },
    marginT9: { marginTop: 9 },
    marginB9: { marginBottom: 9 },

    margin10: { margin: 10 },
    marginX10: { marginHorizontal: 10 },
    marginY10: { marginVertical: 10 },
    marginL10: { marginLeft: 10 },
    marginR10: { marginRight: 10 },
    marginT10: { marginTop: 10 },
    marginB10: { marginBottom: 10 },

    margin11: { margin: 11 },
    marginX11: { marginHorizontal: 11 },
    marginY11: { marginVertical: 11 },
    marginL11: { marginLeft: 11 },
    marginR11: { marginRight: 11 },
    marginT11: { marginTop: 10 },
    marginB11: { marginBottom: 11 },

    margin12: { margin: 12 },
    marginX12: { marginHorizontal: 12 },
    marginY12: { marginVertical: 12 },
    marginL12: { marginLeft: 12 },
    marginR12: { marginRight: 12 },
    marginT12: { marginTop: 12 },
    marginB12: { marginBottom: 12 },

    margin16: { margin: 16 },
    marginX16: { marginHorizontal: 16 },
    marginY16: { marginVertical: 16 },
    marginL16: { marginLeft: 16 },
    marginR16: { marginRight: 16 },
    marginT16: { marginTop: 16 },
    marginB16: { marginBottom: 16 },
})