import { StyleSheet } from 'react-native';

export const myPadding = StyleSheet.create({
    padding1: { padding: 1 },
    paddingX1: { paddingHorizontal: 1 },
    paddingY1: { paddingVertical: 1 },
    paddingL1: { paddingLeft: 1 },
    paddingR1: { paddingRight: 1 },
    paddingT1: { paddingTop: 1 },
    paddingB1: { paddingBottom: 1 },

    padding2: { padding: 2 },
    paddingX2: { paddingHorizontal: 2 },
    paddingY2: { paddingVertical: 2 },
    paddingL2: { paddingLeft: 2 },
    paddingR2: { paddingRight: 2 },
    paddingT2: { paddingTop: 2 },
    paddingB2: { paddingBottom: 2 },

    padding3: { padding: 3 },
    paddingX3: { paddingHorizontal: 3 },
    paddingY3: { paddingVertical: 3 },
    paddingL3: { paddingLeft: 3 },
    paddingR3: { paddingRight: 3 },
    paddingT3: { paddingTop: 3 },
    paddingB3: { paddingBottom: 3 },

    padding4: { padding: 4 },
    paddingX4: { paddingHorizontal: 4 },
    paddingY4: { paddingVertical: 4 },
    paddingL4: { paddingLeft: 4 },
    paddingR4: { paddingRight: 4 },
    paddingT4: { paddingTop: 4 },
    paddingB4: { paddingBottom: 4 },

    padding5: { padding: 5 },
    paddingX5: { paddingHorizontal: 5 },
    paddingY5: { paddingVertical: 5 },
    paddingL5: { paddingLeft: 5 },
    paddingR5: { paddingRight: 5 },
    paddingT5: { paddingTop: 5 },
    paddingB5: { paddingBottom: 5 },

    padding6: { padding: 6 },
    paddingX6: { paddingHorizontal: 6 },
    paddingY6: { paddingVertical: 6 },
    paddingL6: { paddingLeft: 6 },
    paddingR6: { paddingRight: 6 },
    paddingT6: { paddingTop: 6 },
    paddingB6: { paddingBottom: 6 },

    padding7: { padding: 7 },
    paddingX7: { paddingHorizontal: 7 },
    paddingY7: { paddingVertical: 7 },
    paddingL7: { paddingLeft: 7 },
    paddingR7: { paddingRight: 7 },
    paddingT7: { paddingTop: 7 },
    paddingB7: { paddingBottom: 7 },

    padding8: { padding: 8 },
    paddingX8: { paddingHorizontal: 8 },
    paddingY8: { paddingVertical: 8 },
    paddingL8: { paddingLeft: 8 },
    paddingR8: { paddingRight: 8 },
    paddingT8: { paddingTop: 8 },
    paddingB8: { paddingBottom: 8 },

    padding9: { padding: 9 },
    paddingX9: { paddingHorizontal: 9 },
    paddingY9: { paddingVertical: 9 },
    paddingL9: { paddingLeft: 9 },
    paddingR9: { paddingRight: 9 },
    paddingT9: { paddingTop: 9 },
    paddingB9: { paddingBottom: 9 },

    padding10: { padding: 10 },
    paddingX10: { paddingHorizontal: 10 },
    paddingY10: { paddingVertical: 10 },
    paddingL10: { paddingLeft: 10 },
    paddingR10: { paddingRight: 10 },
    paddingT10: { paddingTop: 10 },
    paddingB10: { paddingBottom: 10 },

    padding11: { padding: 11 },
    paddingX11: { paddingHorizontal: 11 },
    paddingY11: { paddingVertical: 11 },
    paddingL11: { paddingLeft: 11 },
    paddingR11: { paddingRight: 11 },
    paddingT11: { paddingTop: 10 },
    paddingB11: { paddingBottom: 11 },

    padding12: { padding: 12 },
    paddingX12: { paddingHorizontal: 12 },
    paddingY12: { paddingVertical: 12 },
    paddingL12: { paddingLeft: 12 },
    paddingR12: { paddingRight: 12 },
    paddingT12: { paddingTop: 12 },
    paddingB12: { paddingBottom: 12 },

    padding16: { padding: 16 },
    paddingX16: { paddingHorizontal: 16 },
    paddingY16: { paddingVertical: 16 },
    paddingL16: { paddingLeft: 16 },
    paddingR16: { paddingRight: 16 },
    paddingT16: { paddingTop: 16 },
    paddingB16: { paddingBottom: 16 },
})